name: Deploy Glue Script to S3

on:
  push:
    branches: [main]  # or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1  # change if you're using a different region

      - name: Upload Glue scripts to S3
        run: |
          aws s3 cp glue_job_script.py s3://glubucket004/glue_job_script.py