name: Deploy Glue Script to S3

on:
  push:
    branches: [main]  # or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: github-glue-deploy
          aws-secret-access-key: Uday@12345
          aws-region: us-east-1  # change if you're using a different region

      - name: Upload Glue scripts to S3
        run: |
          aws s3 cp glue_job_script.py s3://my-glue-job-bucket004/scripts/glue_job_script.py